#!/bin/zsh

# options
setopt PROMPT_SUBST       # bash compatibility. If the PROMPT_SUBST option is set, the prompt string is first subjected to parameter expansion, command substitution and arithmetic expansion
setopt NO_BEEP

setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt INC_APPEND_HISTORY # works like APPEND_HISTORY except that new history lines are added to the $HISTFILE incrementally (as soon as they are entered), rather than waiting until the shell exits.
setopt EXTENDED_HISTORY   # Save each command’s beginning timestamp (in seconds since the epoch) and the duration (in seconds) to the history file.
setopt CORRECT            # Try to correct the spelling of commands.

setopt PATH_DIRS          # Perform a path search even on command names with slashes in them. Thus if ‘/usr/local/bin’ is in the user’s path, and he or she types ‘X11/xinit’, the command ‘/usr/local/bin/X11/xinit’ will be executed (assuming it exists).

autoload -U colors
colors

autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git hg fossil
zstyle ':vcs_info:*' actionformats '%F{5}(%f%s%F{5})%F{3}-%F{5}[%F{2}%b%F{3}|%F{1}%a%F{5}]%f '
zstyle ':vcs_info:*' formats '%F{5}(%f%s%F{5})%F{3}-%F{5}[%F{2}%b%F{5}]%f '
zstyle ':vcs_info:(sv[nk]|bzr):*' branchformat '%b%F{1}:%F{3}%r'


autoload -U promptinit && promptinit
PS1='%{$fg[green]%}(%{$fg[white]%}%*%{$fg[green]%})[%(!.$fg[red].$fg[yellow])%n%{$fg[green]%}@%{$fg[green]%}%m%{$fg[green]%}]%(?.. $fg[red]%? )%{$fg[white]%}%~
%{$fg[green]%}${vcs_info_msg_0_}%{$fg[blue]%}${_docker_machine}%{$reset_color%}%(!.#.$) '

PROMPT='%F{green}'$USER'%f'
PROMPT+='%F{yellow} %~ % %f > '
