#!/bin/bash

# Create a new directory and enter it
mkd() {
	mkdir -p "$@"
  cd "$@"
}

# open up dotfiles in code
alias dotfiles='code $DOTFILES'

aws-auth() {
  # print available accounts
  aws profiles 
  printf "\nwhich account?\n"
  read -r profile
  export AWS_SDK_LOAD_CONFIG=1
  export AWS_PROFILE="$profile" && echo "authed into $AWS_PROFILE"
  aws sso login
}

aws() {
  case $* in
  # what profiles are available to me?
  profiles) command aws --no-cli-pager configure list-profiles ;;
  # who am I authed as?
  auth) command aws sts get-caller-identity ;;
  # what is the arn I am authed as?
  who) command aws sts get-caller-identity --query "Arn" --output text ;;
  # quick auth to ECR
  "ecr "*dkr.ecr.*.amazonaws.com*) command aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin "$2" ;;
  # run default command
  *) command aws "$@" ;;
  esac
}

kc() {
  case $* in
  gp) command kubectl get pods ;;
  # get Prometheus links
  gl) command kubectl get svc -n platform-enablement -l provided-by=jupiter -o=custom-columns=Service:.metadata.name,Endpoint:.spec.externalName ;;
  # print deployment 
  dd) command kubectl describe deployment ;;
  # run default command
  *) command kubectl "$@" ;;
  esac
}

# Query Wikipedia via console over DNS
mwiki() {
	dig +short txt "$*".wp.dg.cx
}

# Get colors in manual pages
man() {
	env \
		LESS_TERMCAP_mb="$(printf '\e[1;31m')" \
		LESS_TERMCAP_md="$(printf '\e[1;31m')" \
		LESS_TERMCAP_me="$(printf '\e[0m')" \
		LESS_TERMCAP_se="$(printf '\e[0m')" \
		LESS_TERMCAP_so="$(printf '\e[1;44;33m')" \
		LESS_TERMCAP_ue="$(printf '\e[0m')" \
		LESS_TERMCAP_us="$(printf '\e[1;32m')" \
		man "$@"
}
