#!/bin/zsh

# go to folder path without using cd.
setopt AUTO_CD

# source external files.
files=(
  "$DOTFILES/aliases/aliases"
  "$DOTFILES/prompt/bash_prompt"
  "$DOTFILES/prompt/zsh_prompt"
  "$DOTFILES/work"
)
for file in "${files[@]}"; do
  if [[ -f "$file" ]]; then
    source "$file"
  fi
done
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
